spring.application.name=task

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa_task}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tks}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration